### ISSUE TITLE
Need SomeOne to Create Folders for all Possible Coading Platforms

### ISSUE THREAD

**Issue by TechnicalGeeks20** [TechnicalGeeks20/CompititiveCoading#1]
# Must Include Folders
1. Hacker Rank
2. CodeChef
3. TopCoder
4. International Collegiate Programming Contest (ICPC)
5. Geeks Coding Challenge (GCC)

**Comment by Rohan1904** [comment]
Hey I would like to do It .  Please assign it to me.

**Comment by TechnicalGeeks20** [comment]
Sure You can Proceed .
